// <auto-generated />
using System;
using BoardTaskService.Infrastructure.Persistence.ApplicationContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardTaskService.Infrastructure.Migrations
{
    [DbContext(typeof(BoardTaskDbContext))]
    [Migration("20260728141919_UpdatedColumn")]
    partial class UpdatedColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("boardtask")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardTaskService.Domain.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_board");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_board_project_id_name");

                    b.ToTable("board", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.BoardAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserProjectMappingId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_project_mapping_id");

                    b.HasKey("Id")
                        .HasName("pk_board_access");

                    b.HasIndex("BoardId")
                        .HasDatabaseName("ix_board_access_board_id");

                    b.HasIndex("UserProjectMappingId")
                        .HasDatabaseName("ix_board_access_user_project_mapping_id");

                    b.ToTable("board_access", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.BoardTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeBoardAccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_board_access_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("priority_id");

                    b.Property<Guid>("TaskTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_column_id");

                    b.HasKey("Id")
                        .HasName("pk_board_task");

                    b.HasIndex("AssigneeBoardAccessId")
                        .HasDatabaseName("ix_board_task_assignee_board_access_id");

                    b.HasIndex("WorkflowColumnId")
                        .HasDatabaseName("ix_board_task_workflow_column_id");

                    b.ToTable("board_task", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.ToTable("project", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_task_comment");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_comment_task_id");

                    b.ToTable("task_comment", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.UserProjectMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_project_mapping");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_user_project_mapping_project_id");

                    b.ToTable("user_project_mapping", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.WorkflowColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid[]>("RoleId")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("role_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_workflow_column");

                    b.HasIndex("BoardId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_column_board_id_name");

                    b.ToTable("workflow_column", "boardtask");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.Board", b =>
                {
                    b.HasOne("BoardTaskService.Domain.Models.Project", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.BoardAccess", b =>
                {
                    b.HasOne("BoardTaskService.Domain.Models.Board", "Board")
                        .WithMany("BoardAccesses")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_access_board_board_id");

                    b.HasOne("BoardTaskService.Domain.Models.UserProjectMapping", "UserProjectMapping")
                        .WithMany("BoardAccesses")
                        .HasForeignKey("UserProjectMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_access_user_project_mapping_user_project_mapping_id");

                    b.Navigation("Board");

                    b.Navigation("UserProjectMapping");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.BoardTask", b =>
                {
                    b.HasOne("BoardTaskService.Domain.Models.BoardAccess", "AssigneeBoardAccess")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeBoardAccessId")
                        .HasConstraintName("fk_board_task_board_access_assignee_board_access_id");

                    b.HasOne("BoardTaskService.Domain.Models.WorkflowColumn", "WorkflowColumn")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_task_workflow_column_workflow_column_id");

                    b.Navigation("AssigneeBoardAccess");

                    b.Navigation("WorkflowColumn");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.TaskComment", b =>
                {
                    b.HasOne("BoardTaskService.Domain.Models.BoardTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_comment_board_task_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.UserProjectMapping", b =>
                {
                    b.HasOne("BoardTaskService.Domain.Models.Project", "Project")
                        .WithMany("UserProjectMappings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_project_mapping_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.WorkflowColumn", b =>
                {
                    b.HasOne("BoardTaskService.Domain.Models.Board", "Board")
                        .WithMany("WorkflowColumns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_column_board_board_id");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.Board", b =>
                {
                    b.Navigation("BoardAccesses");

                    b.Navigation("WorkflowColumns");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.BoardAccess", b =>
                {
                    b.Navigation("AssignedTasks");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.BoardTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.Project", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("UserProjectMappings");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.UserProjectMapping", b =>
                {
                    b.Navigation("BoardAccesses");
                });

            modelBuilder.Entity("BoardTaskService.Domain.Models.WorkflowColumn", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
