<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
  <PackageReference Include="Google.Protobuf" />
  <PackageReference Include="Grpc.Core.Api" />
  <PackageReference Include="Grpc.Net.ClientFactory" />
  <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\Shared.Common\Shared.Common.csproj" />
  <ProjectReference Include="..\Shared.Logging\Shared.Logging.csproj" />
</ItemGroup>
   <ItemGroup>
    <Protobuf Include="Proto\**\*.proto" rpcServices="Both" ProtoRoot="Proto" Access="Public" />
  </ItemGroup>

</Project>
