<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4ce2f2d2-a7ce-47ac-8e9a-58de93f1f91a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Grpc.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared.Authorization\Shared.Authorization.csproj" />
    <ProjectReference Include="..\..\Shared.Exceptions\Shared.Exceptions.csproj" />
    <ProjectReference Include="..\..\Shared.Grpc\Shared.Grpc.csproj" />
    <ProjectReference Include="..\..\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\IdentityService.Application\IdentityService.Application.csproj" />
    <ProjectReference Include="..\IdentityService.Infrastructure\IdentityService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
